---
dependencies:
- role:    freebsd/etc/make.conf-default_versions
  python:  2.7
  python2: 2.7

- freebsd/etc/motd
- freebsd/etc/rc.conf.d/hostname
- freebsd/etc/rc.conf.d/network
- freebsd/etc/rc.conf.d/routing
- freebsd/etc/sysctl.conf/hw.syscons.bell

- freebsd/port/beadm
- freebsd/port/portmaster
- freebsd/port/rsync
- freebsd/port/sudo

- julie
