---
- name: clone home
  git:  repo={{ julie_home_repo }}
        dest={{ julie_home_path }}
        force=no
        update=no

- name: link home to .julie
  file: src={{ julie_home_path }}
        dest={{ julie_home_link }}
        state=link

- name: link dotfiles
  file: src={{ julie_home_path }}/{{ item.src }}
        dest=~/{{ item.dest }}
        state=link
  with_items: julie_home_sublinks
