---
- name: home filesystem
  tags: file-server
  become: yes
  zfs:  name={{ zpool|mandatory }}{{ home_root|mandatory }}
        state=present

- name:       user home filesystems
  tags:       file-server
  become: yes
  zfs:        name={{ zpool|mandatory }}{{ home_root|mandatory }}/{{ item.name|mandatory }}
              quota={{ item.quota | default(none) }}
              state=present
  with_items: home_users|mandatory

- name:       user home filesystems permissions
  tags:       file-server
  become: yes
  file:       name={{ home_root|mandatory }}/{{ item.name|mandatory }}
              owner={{ item.name|mandatory }}
              group=0
              "mode=u+rwX,g+rX,o="
              state=directory
              recurse=yes
  with_items: home_users|mandatory

- name:       assign user homes
  tags:       file-server
  become: yes
  user:       name={{ item.name|mandatory }}
              home={{ home_root|mandatory }}/{{ item.name|mandatory }}
  with_items: home_users|mandatory
