---
- name: copy configs to /usr/local/etc
  tags: openvpn
  become: yes
  notify: openvpn restarted
  command: >
    rsync -rcip "{{ easyrsa_client_cert_path }}/openvpn/" /usr/local/etc/openvpn/

- include: '../../tasks/chroot-dirs.yml'
