#!/bin/sh

if [ `id -u` != 0 ]; then
    echo Must be root >&2
    exit 1
fi

JAILS=/usr/jails
JAILMASTER=$JAILS/master
ZROOT=zroot

SELFDIR=$(cd -- $(dirname $0) && pwd)
INSTALL_LOG=/tmp/installworld.log

if ! zfs list $JAILS >/dev/null 2>&1; then
    zfs create -o atime=off $ZROOT$JAILS
fi

if ! [ -d $JAILMASTER ]; then
    mkdir $JAILMASTER
fi

[ -e $INSTALL_LOG ] && rm $INSTALL_LOG

make -C/usr/src                         \
     installworld                       \
     SRCCONF=$SELFDIR/installworld.conf \
     DESTDIR=$JAILMASTER                \
     2>&1 | tee $INSTALL_LOG || exit 1

