---
dependencies:
- role:     freebsd/etc/make.conf-line
  variable: "{{ name }}_SET"
  value:    "{{ set }}"

- role:     freebsd/etc/make.conf-line
  variable: "{{ name }}_UNSET"
  value:    "{{ unset }}"

