---
dependencies:
- role:     freebsd/portsnap
  tags:     port
- role:     freebsd/etc/make.conf-line
  tags:     port
  variables:
  - var:   "{{ uniquename | default(name) }}_SET"
    value: "{{ set }}"
  - var:   "{{ uniquename | default(name) }}_UNSET"
    value: "{{ unset }}"

