---
dependencies:
- role:     freebsd/portsnap
- role:     freebsd/etc/make.conf-line
  variables:
  - var:   "{{ name }}_SET"
    value: "{{ set }}"
  - var:   "{{ name }}_UNSET"
    value: "{{ unset }}"

