---
- name: easyrsa directory exists
  tags: easy-rsa
  sudo: yes
  file: dest={{ keydir | default(easyrsa_keydir) | mandatory }}/
        state=directory

- name: vars file exists
  tags: easy-rsa
  sudo: yes
  template:
    dest={{ keydir | default(easyrsa_keydir) | mandatory  }}/vars
    src=vars.j2

- name: certs exists
  tags: easy-rsa
  sudo: yes
  easyrsa_cert:
    ca_root={{ keydir | default(easyrsa_keydir) | mandatory }}
    cn={{ item.cn }}
    state={{ item.state | default('present') }}
  with_items: certs
