---
- name:     mDNSResponder.conf
  sudo:     yes
  notify:   restart mdnsresponder
  template: src=mDNSResponder.conf
            dest=/usr/local/etc/

- name:    mdnsresponderposix service enabled
  service: name=mdnsresponderposix enabled=yes
  sudo:    yes

# assumes the previous task created
# the mdnsresponder_enabled line
- name:       mdnsresponderposix rc.conf.local flags
  sudo:       yes
  notify:     restart mdnsresponderposix
  lineinfile: dest=/etc/rc.conf.local
              regexp='^mdnsresponderposix_flags='
              insertafter='^mdnsresponderposix_enable='
              line='mdnsresponderposix_flags="-f /usr/local/etc/mDNSResponder.conf"'

- name:    mdnsresponderposix started
  service: name=mdnsresponderposix state=started
  sudo:    yes

