---
openvpn:
  name:   openvpn
  dev:    tun0
  proto:  udp
  status: /var/log/openvpn.status
  ipv4:
    network: 10.20.1.0
    mask:    255.255.255.0

openvpn_tcp:
  name:        openvpn_tcp
  dev:         tun1
  proto:       tcp
  tcp_nodelay: true
  status:      /var/log/openvpn_tcp.status
  ipv4:
    network: 10.20.2.0
    mask:    255.255.255.0

openvpn_cipher:      AES-128-CBC
openvpn_comp_lzo:    true
openvpn_max_clients: 16
