---
- name:     mDNSResponder.conf
  notify:   restart mdnsresponder
  template: src=mDNSResponder.conf
            dest=/usr/local/etc/

- name:    mdnsresponder service enabled
  service: name=mdnsresponder enabled=yes

# assumes the previous task created
# the mdnsresponder_enabled line
- name:       mdnsresponder rc.conf.local flags
  notify:     restart mdnsresponder
  lineinfile: dest=/etc/rc.conf.local
              regexp='^mdnsresponder_flags='
              insertafter='^mdnsresponder_enable='
              line='mdnsresponder_flags="-f /usr/local/etc/mDNSResponder.conf"'

- name:    mdnsresponder started
  service: name=mdnsresponder state=started

