---
- name:     mDNSResponder.conf
  become: yes
  notify:   restart mdnsresponder
  template: src=mDNSResponder.conf
            dest=/usr/local/etc/

- name:    mdnsresponderposix service enabled
  service: name=mdnsresponderposix enabled=yes
  become: yes

# assumes the previous task created
# the mdnsresponder_enabled line
- name:       mdnsresponderposix rc.conf.local flags
  become: yes
  notify:     restart mdnsresponderposix
  lineinfile: dest=/etc/rc.conf.local
              regexp='^mdnsresponderposix_flags='
              insertafter='^mdnsresponderposix_enable='
              line='mdnsresponderposix_flags="-f /usr/local/etc/mDNSResponder.conf"'

- name:    mdnsresponderposix started
  service: name=mdnsresponderposix state=started
  become: yes

