---
- name:   afp.conf
  become: yes
  notify: restart netatalk
  ini_file: >
    dest='{{ afp_conf_path }}'
    section=Global
    option='{{ item.key }}'
    value='{{ item.value }}'
  with_items: afp_global

- name:     netatalk enabled and started
  become: yes
  service:  name=netatalk
            enabled=yes
            state=started


