#!/bin/sh

if [ -z "$1" ]; then
    echo usage: $0 hostname >&2
    exit 1
fi

if [ `id -u` != 0 ]; then
    echo Must be root >&2
    exit 1
fi

UNAME=$(uname)
HOSTNAME=$1
JACHYMKO=$(cd -- $(dirname $0) && pwd -P)

trycd() {
    cd $1 >/dev/null 2>&1
}

copydir() {
    if [ -d $1 ]; then
        find $1      -type d -print0 | xargs -I{} -0 mkdir -pv /{}
        find $1 -not -type d -print0 | xargs -I{} -0 cp -v {} /{}
    fi
}

provision_dirs() {
    if trycd $1; then
        copydir etc
        copydir root
        copydir usr
    fi
}

provision_script() {
    if [ -x "$1/$2" ]; then
        $1/$2 $HOSTNAME
    fi
}

# Copy all platform- and host-specific files
provision_dirs $JACHYMKO/$UNAME
provision_dirs $JACHYMKO/$UNAME/host-$HOSTNAME

provision_script $JACHYMKO/$UNAME                install-network
provision_script $JACHYMKO/$UNAME/host-$HOSTNAME install-network

provision_script $JACHYMKO/$UNAME                install-machine
provision_script $JACHYMKO/$UNAME/host-$HOSTNAME install-machine
