#!/usr/bin/env zsh

function install() {
    if [[ -e $2 || -L $2 ]] then
        unlink $2
    fi

    [[ -e $1 ]] && ln -sv $1 $2
}

[[ -z "$JACHYMKO" ]] && JACHYMKO=$(echo `dirname $0`(:A))
[[ -z "$prefix"   ]] && prefix=~

install $JACHYMKO             $prefix/.jachymko
install $JACHYMKO/gitconfig   $prefix/.gitconfig
install $JACHYMKO/gitignore   $prefix/.gitignore
install $JACHYMKO/tmux.conf   $prefix/.tmux.conf
install $JACHYMKO/tmux.master $prefix/.tmux.master
install $JACHYMKO/tmux.shared $prefix/.tmux.shared
install $JACHYMKO/vim         $prefix/.vim
install $JACHYMKO/vimrc       $prefix/.vimrc
install $JACHYMKO/zlogin      $prefix/.zlogin
install $JACHYMKO/zshenv      $prefix/.zshenv
install $JACHYMKO/zshrc       $prefix/.zshrc
