#!/bin/sh

SELFDIR=$(cd -- $(dirname $0) && pwd)
UNAME=$(uname)

dot_link() {
    if [ -e ~/$2 ]; then
        rm ~/$2
    fi

    if [ -e $SELFDIR/$1 ]; then
        echo link ~/$2 -\> $SELFDIR/$1
        ln -s $SELFDIR/$1 ~/$2
    fi
}

dot_copy() {
    if [ -e ~/$2 ]; then
        rm ~/$2
    fi

    if [ -e $SELFDIR/$1 ]; then
        echo copy $SELFDIR/$1 -\> ~/$2
        cp -f $SELFDIR/$1 ~/$2
    fi
}

if [ ! -e ~/.jachymko ]; then
    dot_link . .jachymko
fi

# gitconfig is copied because uname/install-jachymko scripts modify it
dot_copy gitconfig      .gitconfig
dot_link gitignore      .gitignore
dot_link ircrc          .ircrc
dot_link offlineimaprc  .offlineimaprc
dot_link tmux/tmux.conf .tmux.conf
dot_link vim            .vim
dot_link vim/vimrc      .vimrc
dot_link vim/gvimrc     .gvimrc
dot_link zlogin         .zlogin
dot_link zshenv         .zshenv
dot_link zshrc          .zshrc

if [ -r "$SELFDIR/$UNAME/install-jachymko" ]; then
    . $SELFDIR/$UNAME/install-jachymko
fi
