#!/bin/sh

if [ `id -u` != 0 ]
then
    echo Must be root >&2
    exit 1
fi

# 1. Create the necessary partitions on the disk(s) and add ZFS aware boot code.
#
#       gpart create -s gpt ada0
#       gpart add -t freebsd-boot -s 94 ada0
#       gpart add -t freebsd-zfs -l disk0 ada0
#       gpart bootcode -b /boot/pmbr -p /boot/gptzfsboot -i 1 ada0
#
# 2. Create the pool
#
#       zpool create -m /mnt zroot /dev/gpt/disk0
#
# 3. Run this script
#
#       fetch -o - http://goo.gl/RPx9OV | sh

# ============================================================================================
# Configuration
# ============================================================================================

    SWAP=${SWAP-2G}                  # swap dataset size
   ZPOOL=${ZPOOL-zroot}              # ZFS pool name
 BE_ROOT=${ZPOOL}/ROOT               # boot environment container dataset
BOOT_ENV=${BE_ROOT}/default          # the default boot environment dataset

DESTDIR=${DESTDIR-/mnt}              # mount point for the new filesystem
DISTDIR=${DISTDIR-/usr/freebsd-dist} # where the FreeBSD distribution files are

WHEEL_USERS=${WHEEL_USERS-julie}     # name of the users to be created and added
                                     # to the wheel group

# Ensure zpool $ZPOOL exists
zpool status $ZPOOL >/dev/null || exit $?

# ============================================================================================
# ZFS creation
# ============================================================================================

echo Disable access time.
zfs set atime=off ${ZPOOL}

echo Make sure pool root is not mounted.
zfs set mountpoint=none ${ZPOOL}

if [ "${SWAP}" ]
then
    echo Create ${SWAP} swap zvol.
    zfs create -o checksum=off -o org.freebsd:swap=on -V ${SWAP} ${ZPOOL}/swap
fi

echo Create {$BE_ROOT} container for boot environments
zfs create -o mountpoint=none ${BE_ROOT}

echoe Create the default boot environment ${BOOT_ENV}
zfs create -o mountpoint=${DESTDIR} ${BOOT_ENV}

COMP="compression=on"; NOCOMP="compression=off"
EXEC="exec=on";        NOEXEC="exec=off"
SUID="setuid=on";      NOSUID="setuid=off"

# These datasets are part of the boot environment
zfs create -o   ${EXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/tmp
zfs create -o   ${EXEC} -o   ${SUID} -o ${NOCOMP} ${BOOT_ENV}/usr
zfs create -o ${NOEXEC} -o ${NOSUID} -o ${NOCOMP} ${BOOT_ENV}/var
zfs create -o ${NOEXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/var/crash
zfs create -o ${NOEXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/var/db
zfs create -o   ${EXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/var/db/pkg
zfs create -o ${NOEXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/var/log
zfs create -o ${NOEXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/var/mail
zfs create -o ${NOEXEC} -o ${NOSUID} -o ${NOCOMP} ${BOOT_ENV}/var/run
zfs create -o   ${EXEC} -o ${NOSUID} -o   ${COMP} ${BOOT_ENV}/var/tmp

# These datasets aren't part of the boot environment
zfs create -o   ${EXEC} -o ${NOSUID} -o ${NOCOMP} -o mountpoint=${DESTDIR}/home      ${ZPOOL}/home
zfs create -o   ${EXEC} -o ${NOSUID} -o   ${COMP} -o mountpoint=${DESTDIR}/usr/ports ${ZPOOL}/usr.ports
zfs create -o ${NOEXEC} -o ${NOSUID} -o   ${COMP} -o mountpoint=${DESTDIR}/usr/src   ${ZPOOL}/usr.src
zfs create -o ${NOEXEC} -o ${NOSUID} -o ${NOCOMP} -o mountpoint=${DESTDIR}/var/empty ${ZPOOL}/var.empty

zfs create -o ${NOEXEC} -o ${NOSUID} -o ${NOCOMP} ${ZPOOL}/usr.ports/distfiles
zfs create -o ${NOEXEC} -o ${NOSUID} -o ${NOCOMP} ${ZPOOL}/usr.ports/packages

zfs list -o name,exec,setuid,compression,mountpoint
read

echo Set the boot environemnt ${BOOT_ENV} as bootfs
zpool set bootfs=${BOOT_ENV} ${ZPOOL}

echo Re-import the pool using known cache file--will be copied to $DESTDIR/boot when done.
zpool export ${ZPOOL}
zpool import -o cachefile=/var/tmp/zpool.cache ${ZPOOL}

# ============================================================================================
# FreeBSD Installation
# ============================================================================================

echo FreeBSD Installation
cd $DESTDIR

# Install FreeBSD
for file in base.txz kernel.txz
do
    echo "Extracting $file to $DESTDIR"
    tar -xpf $DISTDIR/$file
done

echo Create an empty fstab file
touch etc/fstab

echo Setting tmp and var/tmp permissions
# sticky = unprivileged users may not delete or rename files of other users
chmod 1777 tmp
chmod 1777 var/tmp

echo Copy zpool.cache so the boot loader is able to locate the pool.
cp /var/tmp/zpool.cache boot/zfs/zpool.cache

echo Enable ZFS in the loader.
echo 'zfs_load="YES"'                         >> boot/loader.conf
echo "vfs.root.mountfrom=\"zfs:${BOOT_ENV}\"" >> boot/loader.conf

echo Enable sshd and zfs services
echo 'sshd_enable="YES"' >> etc/rc.conf.d/sshd
echo 'zfs_enable="YES"'  >> etc/rc.conf.d/zfs

# ============================================================================================
# Create users
# ============================================================================================

for user in $WHEEL_USERS
do
    echo Add wheel user $user
    chroot $DESTDIR /usr/sbin/pw useradd $user -g wheel
    chroot $DESTDIR /usr/bin/passwd $user < /dev/tty

    echo Create $DESTDIR/home/$user
    mkdir home/$user

    echo Change ownership of $DESTDIR/home/$user
    chroot $DESTDIR /usr/sbin/chown -R $user:wheel /home/$user
done

echo FreeBSD has been installed to $DESTDIR
echo Unmounting filesystems...

cd /
zfs umount -a

zfs set mountpoint=legacy      ${BOOT_ENV}

zfs set mountpoint=/home       ${ZPOOL}/home
zfs set mountpoint=/usr/ports  ${ZPOOL}/usr.ports
zfs set mountpoint=/usr/src    ${ZPOOL}/usr.src
zfs set mountpoint=/var/empty  ${ZPOOL}/var.empty
zfs set readonly=on            ${ZPOOL}/var.empty

echo Done. Type 'reboot' to restart the machine.
