#!/usr/bin/env zsh

if [[ -z "$JACHYMKO" ]]; then
	typeset JACHYMKO=`echo $0/..(:A)`
fi

typeset -A FILES
set -A FILES \
	$JACHYMKO            ~/.jachymko  \
	$JACHYMKO/gitconfig  ~/.gitcofig  \
	$JACHYMKO/tmux.conf  ~/.tmux.conf \
	$JACHYMKO/zsh/zlogin ~/.zlogin    \
	$JACHYMKO/zsh/zshenv ~/.zshenv    \
	$JACHYMKO/zsh/zshrc  ~/.zshrc     \

for f in ${(k)FILES}; do
	target=$FILES[$f]
	[[ -e $target ]] && rm -fr $target
	ln -sv $f $target
done
