#!/usr/bin/env zsh

function install() {
    if [[ -e $2 || -L $2 ]] then
        unlink $2
    fi

    [[ -e $1 ]] && ln -sv $1 $2
}

[[ -z "$JACHYMKO" ]] && JACHYMKO=$(echo `dirname $0`(:A))
[[ -z "$prefix"   ]] && prefix=~

if [[ ! -e $prefix/.jachymko ]]; then
    install $JACHYMKO $prefix/.jachymko
fi

install $JACHYMKO/gitconfig      $prefix/.gitconfig
install $JACHYMKO/gitignore      $prefix/.gitignore
install $JACHYMKO/ircrc          $prefix/.ircrc
install $JACHYMKO/tmux/tmux.conf $prefix/.tmux.conf
install $JACHYMKO/tmuxinator     $prefix/.tmuxinator
install $JACHYMKO/vim            $prefix/.vim
install $JACHYMKO/vim/vimrc      $prefix/.vimrc
install $JACHYMKO/zlogin         $prefix/.zlogin
install $JACHYMKO/zshenv         $prefix/.zshenv
install $JACHYMKO/zshrc          $prefix/.zshrc

if [[ -x "$JACHYMKO/`uname`/install-jachymko" ]]; then
    "$JACHYMKO/`uname`/install-jachymko"
fi
