#!/bin/sh

JACHYMKO=$(cd -- $(dirname $0) && pwd -P)
. ${JACHYMKO}/install-machine.subr

while getopts 'f' opt; do
    case $opt in
        f)  FILES_ONLY=true;;
        \?) echo Unknown option: -$OPTARG >&2; exit 1;;
    esac
done
shift $((OPTIND-1))

UNAME=$(uname)
HOSTNAME=${1-$(hostname -s)}

if [ -z "$HOSTNAME" ]; then
    echo usage: $0 [-f] [hostname] >&2
    echo        -f          only copies config files >&2
    echo        hostname    can be ommited if this machine already has one >&2
    exit 1
fi

# Copy all platform- and host-specific files
provision_dirs "$JACHYMKO/$UNAME"
provision_dirs "$JACHYMKO/$UNAME/host-$HOSTNAME"

provision_script "$JACHYMKO/$UNAME"                install-files
provision_script "$JACHYMKO/$UNAME/host-$HOSTNAME" install-files

if [ -n "$FILES_ONLY" ]; then
    exit 0
fi

provision_script "$JACHYMKO/$UNAME"                install-network
provision_script "$JACHYMKO/$UNAME/host-$HOSTNAME" install-network

provision_script "$JACHYMKO/$UNAME"                install-machine
provision_script "$JACHYMKO/$UNAME/host-$HOSTNAME" install-machine
