#!/bin/sh

RESOLVCONF=/sbin/resolvconf

case ${1} in
    up)
        env | awk '
        BEGIN {
            has_search = 0
        }
        /^foreign_option_([0-9]+)=dhcp-option (DNS|DOMAIN|DOMAIN-SEARCH) (.*)$/ {
            if ($2 == "DNS") {
                nameserver[$1] = $3
            }
            else {
                search[$1] = $3
                has_search = 1
            }
        }
        END {
            for (i in nameserver) {
                printf("nameserver %s\n", nameserver[i])
            }

            if (has_search != 0) {
                printf("search ")
                for (i in search) {
                    printf("%s ", search[i])
                }
                printf("\n")
            }
        }' | ${RESOLVCONF} -a "${dev}.inet"
        ;;
    down)
        ${RESOLVCONF} -d "${dev}.inet"
        ;;
esac
