project_name: 0
project_root: ~/
#socket_name: # Not needed.  Remove to use default socket
#rvm: 1.9.2@rails_project
#pre: sudo /etc/rc.d/mysqld start
tabs:
  - shell:
      layout: even-vertical
      panes:
        - # shell
        - # shell
  - vim: vim
