#!/bin/sh

MACHINE=${MACHINE-$(uname -m)}
KERNCONF=${KERNCONF-$(hostname -s | tr '[:lower:]' '[:upper:]')}
KERNCONF_PATH=/usr/src/sys/$MACHINE/conf/$KERNCONF

LOG=/tmp/buildkernel.log
THISDIR=$(cd -- $(dirname $0) && pwd)

if [ -e $LOG ]; then
    rm $LOG
fi

cp -v $THISDIR$KERNCONF_PATH $KERNCONF_PATH && \
make -C /usr/src KERNCONF=$KERNCONF buildkernel 2>&1 | tee $LOG
