#!/bin/sh

if [ `id -u` -ne 0 ]; then
    echo must be root >&2
    exit 1
fi

ensure_group() {
    if ! pw group show $1 >/dev/null 2>&1; then
        pw group add $1
    fi
}

ensure_svc_user() {
    if ! pw group show $1 >/dev/null 2>&1; then
        pw group add -n $1
    fi

    if ! pw user show $1 >/dev/null 2>&1; then
        pw user add -n $1                     \
                    -d /nonexistent           \
                    -g $1                     \
                    -s /usr/sbin/nologin
    fi
}
