---
- include: ../../tasks/local-line.yml
  tags: [ freebsd, src.conf, without_tcsh ]
  srcconf:
    WITHOUT_TCSH:

- name: get users using /bin/csh
  tags: [ freebsd, src.conf, without_tcsh ]
  shell: "egrep '/bin/t?csh' /etc/passwd | cut -d: -f1"
  register: csh_users
  changed_when: False

- name: set user shells to /bin/sh
  tags: [ freebsd, src.conf, without_tcsh ]
  become: yes
  command: '/usr/bin/chsh -s /bin/sh "{{ item }}"'
  with_items: csh_users.stdout_lines
  register: chsh_result
  changed_when: '"chsh: user information updated" in chsh_result.stdout'
