if has("gui_win32")
    set guifont=Consolas:h14:cEASTEUROPE

    function! ToggleFullscreen()
        call libcallnr("gvimfullscreen.dll", "ToggleFullScreen", 0)
    endfunction

    call ToggleFullscreen()
endif

if has("mac")
    set fullscreen
    set guifont=Menlo:h14
endif

set guioptions=c " c - use console dialogs for simple questions
