---
- name: home filesystem
  zfs: name={{ zpool }}{{ home.root }} state=present

- name: user home filesystems
  zfs: name={{ zpool }}{{ home.root }}/{{ item.name }} state=present quota={{ item.quota }}
  with_items: home.users

- name: user home filesystems permissions
  file: name={{ home.root }}/{{ item.name }}
        state=directory
        owner={{ item.name }}
  with_items: home.users

- name: assign user homes
  user: name={{ item.name }}
        home={{ home.root }}/{{ item.name }}
  with_items: home.users

