---
- name: portsnap periodic
  tags: [ freebsd, portsnap, periodic ]
  become: yes
  copy:
    dest:     /etc/periodic/{{ portsnap_period }}/900.portsnap
    content: "#!/bin/sh\n/usr/sbin/portsnap cron update"
    mode:     0755
