---
- name: .ssh directory
  tags: ssh
  file:
    dest: ~/.ssh
    state: directory

- name: .ssh config files
  tags: ssh
  file:
    dest: "~/.ssh/{{ item }}"
    src: "~/.julie/ssh/{{ item }}"
    state: link
    force: yes
  with_items:
  - config
  - id_rsa.pub
  - known_hosts

- name: private key permissions
  tags: ssh
  file:
    dest: "~/.ssh/{{ item }}"
    state: file
    mode:  0600
  with_items:
  - id_rsa
