---
easyrsa_cadir: /data/easyrsa
easyrsa_cacn:  rsa.juliekoubova.net
easyrsa_keydir: "{{ easyrsa_cadir }}/keys"
easyrsa_server_certs:
- { cn: vpn.juliekoubova.net }
- { cn: irc.juliekoubova.net, group: znc }
easyrsa_certs:
- { user: "{{ ansible_user_id }}", cn: bydlenka }
- { user: "{{ ansible_user_id }}", cn: julie-ip5 }
- { user: "{{ ansible_user_id }}", cn: julie-mba }
- { user: "{{ ansible_user_id }}", cn: julie-mbpr }
