---
# address and network variables are defined in network.yml
# certificate variables are defined in easyrsa.yml

openvpn_udp:
  dev:    tun0
  proto:  udp
  ipv4:
    network: "{{ demonka_openpvn_udp_inet_net }}"
    mask:    "{{ demonka_openpvn_udp_inet_mask }}"
  ipv4_static:
  - { cn: bydlenka, ips: "{{ demonka_openvpn_udp_inet_bydlenka_ips }}" }

openvpn_tcp:
  name:        openvpn_tcp
  dev:         tun1
  proto:       tcp
  tcp_nodelay: true
  chroot:      /var/openvpn_tcp
  status:      /var/log/openvpn_tcp.status
  ipv4:
    network: "{{ demonka_openvpn_tcp_inet_net }}"
    mask:    "{{ demonka_openvpn_tcp_inet_mask }}"

# pf redirects external packets to the internal
# interface
openvpn_bind_ip:     "{{ demonka_int_inet_ip0 }}"
openvpn_cred:
  ca:   "{{ easyrsa_keydir }}/ca.crt"
  cert: "{{ easyrsa_keydir }}/vpn.juliekoubova.net.crt"
  dh:   "{{ easyrsa_keydir }}/dh1024.pem"
  key:  "{{ easyrsa_keydir }}/vpn.juliekoubova.net.key"
openvpn_max_clients: 16
openvpn_push:
- "route {{ demonka_int_inet_net }} {{ demonka_int_inet_mask }} vpn_gateway"
- "dhcp-option DNS {{ demonka_int_inet_ip0 }}"
- "dhcp-option DOMAIN juliekoubova.net"
