---

daemonik_internal_ip: 10.42.1.1
daemonik_udp_vpn_net: 10.42.2.0
daemonik_tcp_vpn_net: 10.42.3.0

openvpn_udp:
  name:   openvpn
  dev:    tun0
  proto:  udp
  status: /var/log/openvpn.status
  ipv4:
    network: "{{ daemonik_udp_vpn_net }}"
    mask:    255.255.255.0

openvpn_tcp:
  name:        openvpn_tcp
  dev:         tun1
  proto:       tcp
  tcp_nodelay: true
  status:      /var/log/openvpn_tcp.status
  ipv4:
    network: "{{ daemonik_tcp_vpn_net }}"
    mask:    255.255.255.0

openvpn_cipher:      AES-128-CBC
openvpn_comp_lzo:    true
openvpn_cred:
  ca:   "{{ easyrsa_keydir }}/keys/ca.pem"
  cert: "{{ easyrsa_keydir }}/keys/vpn.juliekoubova.net.pem"
  dh:   "{{ easyrsa_keydir }}/keys/dh1024.pem"
  key:  "{{ easyrsa_keydir }}/keys/vpn.juliekoubova.net.key"
openvpn_max_clients: 16
openvpn_push:
- route {{ daemonik_internal_ip }} 255.255.255.255 vpn_gateway
- dhcp-option DNS {{ daemonik_internal_ip }}
