---
znc_conf:          demonka.conf.j2
znc_client_certs: "{{ easyrsa_certs }}"

# this is the place on the control machine
# where easyrsa downloads the .sha1 fingerprints to.
# must be kept in sync with host_vars/demonka/easyrsa.yml
znc_client_fingerprint_location: "{{ easyrsa_local_root }}/demonka"

# path on the znc machine where the private+public key file is
znc_ssl_pem:       "{{ easyrsa_keydir }}/irc.juliekoubova.net.pem"
znc_ssl_port:      6697
