---
- name: periodic svn update /usr/src
  tags: [ freebsd, periodic ]
  become: yes
  copy:
    dest:     /etc/periodic/{{ freebsd_svn_period }}/900.svn-update-usr.src
    content: "#!/bin/sh\n{{ freebsd_svn_executable }} update"
    mode:     0755
