---
- name: template
  become: yes
  template: dest=/etc/mergemaster.rc
            src=mergemaster.rc.j2

- name: ignore file
  become: yes
  copy: dest={{ mergemaster_ignore_file }}
        content=""
        force=no
