---
ansible_python_interpreter: /usr/local/bin/python2.7
data_root:                  /data
freebsd_makeconf_unset:     DOCS EXAMPLES NLS X11
freebsd_svn_server:         svn0.eu.FreeBSD.org
freebsd_svn_branch:         stable/10
freebsd_svn_period:         daily
sasl_authmech:              getpwent
sshd_password_auth:         no
sshd_port:                  37157
sshd_use_pam:               no
zpool:                      zroot
zfs:
- name: "{{ zpool }}{{ data_root }}"
  mountpoint: "{{ data_root }}"
