---
- name: fetch
  tags: portsnap
  sudo: yes
  command: /usr/sbin/portsnap fetch
  register: portsnap_fetch_result
  changed_when: "'No updates needed.' not in portsnap_fetch_result.stdout"

- name: does ports tree exist?
  tags: portsnap
  stat:
    path: /usr/ports/INDEX-10
    get_md5: no
  register: ports_index

- name: extract
  tags: portsnap
  sudo: yes
  command: /usr/sbin/portsnap extract
  when: not ports_index.stat.exists

- name: update
  tags: portsnap
  sudo: yes
  command: /usr/sbin/portsnap update
  when: portsnap_fetch_result|success
  register: portsnap_update_result
  changed_when: "'Ports tree is already up to date.' not in portsnap_update_result.stdout"
