---
dependencies:
- role: ansible
  when: ansible_os_family == 'Darwin'

- role: fortune
- role: git
- role: ranger
- role: tmux
- role: vim
- role: wget
- role: zsh

- role: julie/gitconfig

- role:   julie/torrent-uploader
  source: "{{ ansible_env.HOME }}/Downloads"
  dest:   bydlenka:/data/downloads
  when:   ansible_os_family == 'Darwin'
