---
- name: hostname config
  tags: hostname
  become: yes
  lineinfile:
    dest: /etc/rc.conf.d/hostname
    create: yes
    regexp: ^hostname=
    line: hostname="{{ hostname | default(ansible_fqdn) }}"
