#!/usr/bin/env zsh

if [[ ! -x `which brew` ]]; then
    echo homebrew not installed! >&2
    exit 1
fi

for file ($(dirname $0)/formulae.d/*); do
    formula=$(basename $file)
    formula_opts=$(cat $file)
    if ! brew list $formula > /dev/null; then
        brew install $formula $formula_opts
    else
        brew upgrade $formula $formula_opts
    fi
done

brew linkapps
