#!/usr/bin/env zsh

if [[ ! -x `which brew` ]]; then
    /usr/bin/ruby -e "$(/usr/bin/curl -fsSL https://raw.github.com/mxcl/homebrew/master/Library/Contributions/install_homebrew.rb)" 
fi

for file ($(dirname $0)/formulae.d/*); do
    formula=$(basename $file)
    if ! brew list $formula > /dev/null; then
        brew install $formula `cat $file`
    else
        echo $formula already installed
    fi
done

brew linkapps
