#!/bin/sh

if [ ! -x `which make` ]; then
    echo "Install Xcode!"
    exit 1
fi

get_homebrew=https://raw.github.com/mxcl/homebrew/go
get_rvm=https://get.rvm.io

curl -fsSL $get_homebrew | ruby
curl -fsSL $get_rvm | bash -s stable --ruby

~/.jachymko/Darwin/defaults

hash -r # use the git from homebrew
git config --global credential.helper osxkeychain
