#!/bin/sh

if [ -z "$1" ]; then
    echo usage: $0 hostname >&2
    exit 1
fi

echo "Setting ComputerName, HostName, LocalHostName to $1"

scutil --set ComputerName $1
scutil --set HostName $1
scutil --set LocalHostName $1
