#!/usr/bin/env sh

get_homebrew=https://raw.github.com/mxcl/homebrew/go
get_rvm=https://get.rvm.io

curl -fsSL $get_homebrew | ruby
curl -fsSL $get_rvm | bash -s stable --ruby

~/.jachymko/Darwin/formulae
