---
- name: /etc/make.conf variable
  tags: make.conf
  sudo: yes
  lineinfile:
    dest: /etc/make.conf
    create: yes
    line: "{{ item.var }}={{ item.value }}"
    regexp: "^{{ item.var }}="
  with_items:
  - var:   "{{ variable|mandatory }}"
    value: "{{ value|default('') }}"
  when: item.value|length > 0 and item.var|length > 0
