---
- name: restart netif
  pause:
    prompt: >
      The network settings on {{ ansible_hostname }} have changed.
      Please execute the following command manually:

          sudo sh <<EOF
             service netif restart
             service routing restart
             service dhclient restart <dhcp_interfaces>
          EOF

      Then, press ENTER to continue this playbook.
