---
- name: transmission rc.conf.d
  tags: download-server
  sudo: yes
  notify: restart transmission
  template: >
    dest=/usr/local/etc/rc.conf.d/transmission
    src=rc.conf.d.j2

- name: transmission stopped (would overwrite settings.json)
  tags: download-server
  sudo: yes
  service: name=transmission state=stopped

- name: transmission settings.json
  tags: download-server
  sudo: yes
  notify: restart transmission
  template: >
    dest=/usr/local/etc/transmission/home/settings.json
    owner=transmission
    group={{ downloads_group }}
    src=settings.json.j2

- name: transmission log
  tags: download-server
  sudo: yes
  copy: dest=/var/log/transmission
        content=""
        force=no
        owner=transmission
        group=0
        mode=0640

- name: transmission var dir
  tags: download-server
  sudo: yes
  file: dest=/var/run/transmission
        state=directory
        owner=transmission
        group=0
        mode=0640

- name: ensure transmission member of downloads group
  tags: download-server
  sudo: yes
  user: name=transmission groups={{ downloads_group }} append=yes

- name: remove default transmission group
  tags: download-server
  sudo: yes
  group: name=transmission state=absent

- name: transmission started
  tags: download-server
  sudo: yes
  service: name=transmission state=started
