---
- name: viscosity config dirs
  tags: [ openvpn, viscosity ]
  file:
    dest:  "~{{ item[0].user }}/{{ item[0].client }}/{{ item[1].name }}.visc"
    state: directory
    owner: "{{ item[0].user }}"
  with_nested:
  - openvpn_viscosity.clients
  - openvpn_viscosity.servers

- name: viscosity config files
  tags: [ openvpn, viscosity ]
  template:
    dest:  "~{{ item[0].user }}/{{ item[0].client }}/{{ item[1].name }}.visc/config.conf"
    src:   "../../templates/openvpn.conf.j2"
    owner: "{{ item[0].user }}"
  with_nested:
  - openvpn_viscosity.clients
  - openvpn_viscosity.servers

- name: viscosity ca cert
  tags: [ openvpn, viscosity ]
  command: >
    /bin/cp "{{ easyrsa_keydir }}/ca.crt"
    "~{{ item[0].user }}/{{ item[0].client }}/{{ item[1].name }}.visc/ca.crt"
  args:
    creates: "~{{ item[0].user }}/{{ item[0].client }}/{{ item[1].name }}.visc/ca.crt"
  with_nested:
  - openvpn_viscosity.clients
  - openvpn_viscosity.servers

- name: viscosity client cert files
  tags: [ openvpn, viscosity ]
  command: >
    /bin/cp "{{ easyrsa_keydir }}/{{ item[0].client }}.{{ item[2] }}"
    "~{{ item[0].user }}/{{ item[0].client }}/{{ item[1].name }}.visc/{{ item[0].client }}.{{ item[2] }}"
  args:
    creates: "~{{ item[0].user }}/{{ item[0].client }}/{{ item[1].name }}.visc/{{ item[0].client }}.{{ item[2] }}"
  with_nested:
  - openvpn_viscosity.clients
  - openvpn_viscosity.servers
  - [ crt, key ]
