---
- name:  backup group
  group: name={{ backup_group | mandatory }} state=present

- name: backup group members
  user: name={{ item }} groups={{ backup_group | mandatory }} append=yes
  with_items: backup_users | mandatory

- name: backup dir permissions
  file: name={{ backup_root | mandatory }}
        group={{ backup_group | mandatory }}
        state=directory
        mode=770
