---
- name: install pip
  tags: [ python, pip ]
  become: yes
  easy_install: name=pip

- name: install pip packages
  tags: [ python, pip ]
  become: yes
  pip:  name={{ item }}
  with_items:
  - passlib
  - pyyaml

