---
#
# Create directories for all server configurations. Optionally append an extension,
# Viscosity bundles are directories ending in .visc.
#
- name: config dir
  tags: [ openvpn, openvpn-client-provisioning ]
  file:
    dest:  "~{{ user }}/{{ client }}/{{ dir_prefix }}{{ item.name|default('openvpn') }}{{ dir_ext }}"
    state: directory
    owner: "{{ user }}"
  with_items: servers

#
# Generate the config files. Config name can be overriden, Viscosity uses config.conf.
#
- name: config file
  tags: [ openvpn, openvpn-client-provisioning ]
  template:
    dest:  "~{{ user }}/{{ client }}/{{ dir_prefix }}{{ item.name|default('openvpn') }}{{ dir_ext }}/{{ config_name | default('openvpn.conf') }}"
    src:   "../../templates/openvpn.conf.j2"
    owner: "{{ user }}"
  with_items: servers

#
# Sync the ta-key file
#
- name: tls-auth file
  tags: [ openvpn, openvpn-client-provisioning ]
  become: yes
  command: >
    rsync -ci
    "/usr/local/etc/openvpn/{{ item.instance.name|default('openvpn') }}.ta-key"
    "~{{ user }}/{{ client }}/{{ dir_prefix }}{{ item.name|default('openvpn') }}{{ dir_ext }}/{{ item.instance.name|default('openvpn') }}.ta-key"
  register: rsync_result
  changed_when: "rsync_result.stdout != ''"
  with_items: servers

#
# Set the ta-key file owner and permissions.
#
- name: tls-auth file permissions
  tags: [ openvpn, openvpn-client-provisioning ]
  become: yes
  file:
    dest:  "~{{ user }}/{{ client }}/{{ dir_prefix }}{{ item.name|default('openvpn') }}{{ dir_ext }}/{{ item.instance.name|default('openvpn') }}.ta-key"
    owner: "{{ user }}"
    mode:  0600
  with_items: servers

#
# Sync the CA root cert
#
- name: ca cert
  tags: [ openvpn, openvpn-client-provisioning ]
  command: >
    rsync -ci
    "{{ easyrsa_keydir }}/ca.crt"
    "~{{ user }}/{{ client }}/{{ dir_prefix }}{{ item.name|default('openvpn') }}{{ dir_ext }}/ca.crt"
  register: rsync_result
  changed_when: "rsync_result.stdout != ''"
  with_items: servers

#
# Sync the client cert and key files
#
- name: client cert files
  tags: [ openvpn, openvpn-client-provisioning ]
  command: >
    rsync -ci
    "{{ easyrsa_keydir }}/{{ client }}.{{ item[1] }}"
    "~{{ user }}/{{ client }}/{{ dir_prefix }}{{ item[0].name|default('openvpn') }}{{ dir_ext }}/{{ client }}.{{ item[1] }}"
  register: rsync_result
  changed_when: "rsync_result.stdout != ''"
  with_nested:
  - servers
  - [ crt, key ]
