#!/bin/sh

if [ `id -u` != 0 ]; then
    echo Must be root >&2
    exit 1
fi

# Kill root if sudo installed successfully
if [ "$(logname 2>/dev/null)" != 'root' ]; then
    echo "Disable root login."
    chpass -p \* root
    chpass -p \* toor
fi

root_rw() {
    if [ -f $1 ]; then
        chmod -vv 0600 $1
    fi
}

root_rw /usr/local/etc/racoon/racoon.conf
root_rw /usr/local/etc/racoon/racoon.psk
