#!/bin/sh

if [ -z "$1" ]; then
    echo usage: $0 hostname >&2
    exit 1
fi

if [ `id -u` != 0 ]; then
    echo Must be root >&2
    exit 1
fi

cd $(dirname $0)

./ports $1

if sudo true 2>/dev/null; then
    echo "Disable root login."
    chpass -p \* root
fi

if [ -x "$(which git)" ] && ! git status >/dev/null 2>&1; then

    [ -d ~/src ] || mkdir ~/src || exit 1

    cd ~/src && git clone https://github.com/jachymko/home || exit 1

    if [ -d ~/.jachymko ]; then
        rm -rf ~/.jachymko
    fi
fi

