#!/bin/sh

# .login_conf must not be a symlink
dot_copy FreeBSD/login_conf .login_conf

ZSH_PATH=$(which zsh)
CURRENT_SHELL=$(pw usershow $(logname) | awk -F: '{print $10}')

if [ -x "$ZSH_PATH" ]; then
    if [ "$CURRENT_SHELL" = "$ZSH_PATH" ]; then
        echo Current shell is already $ZSH_PATH
    else
        echo Changing shell to $ZSH_PATH
        chpass -s $ZSH_PATH
    fi

fi
