#!/bin/sh

if [ -z "$1" ]; then
    echo usage: $0 hostname >&2
    exit 1
fi

if [ `id -u` != 0 ]; then
    echo Must be root >&2
    exit 1
fi

cd $(dirname $0)

./ports $1

if sudo true 2>/dev/null; then
    echo "Disable root login."
    chpass -p \* root
fi

if [ -x "$(which git)" ] && ! git status >/dev/null 2>&1; then
    cd ~
    git clone https://github.com/jachymko/home .jachymko-tmp || exit 1
    mv .jachymko .jachymko-old
    mv .jachymko-tmp .jachymko
fi

