#!/bin/csh
set PORTDIR = /usr/ports
set PORTS = ( \
              editors/vim-lite  \
              devel/ruby        \
              devel/ruby-gems   \
              devel/git         \
              shells/zsh        \
              sysutils/tmux     \
              security/sudo     \
              shells/rssh       \
              www/nginx         \
            )

portsnap fetch

foreach action (config-recursive install clean)
	foreach port ($PORTS)
		make -C $PORTDIR/$port $action
	end
end
