---
openvpn_bind_ip:           "{{ ansible_default_ipv4.address }}"
openvpn_cipher:            AES-128-CBC
openvpn_client_config_dir: client-config
openvpn_comp_lzo:          yes
openvpn_dev:               tun
openvpn_keepalive:         10 60
openvpn_max_clients:
openvpn_name:              openvpn
openvpn_port:              1194
openvpn_proto:             udp
openvpn_push:              []
openvpn_reduce_privileges: yes
openvpn_status:            /var/log/openvpn.status
openvpn_tcp_nodelay:       no
