---
- name: site directories
  tags: www
  sudo: yes
  file: dest=/usr/local/etc/nginx/{{ item }}
        state=directory
  with_items:
  - sites-available
  - sites-enabled
  - sites-partials

- name: log directories
  tags: www
  sudo: yes
  file: dest=/var/log/nginx
        state=directory
        owner=www
        group=0
        mode=0770

- name: nginx.conf
  tags: www
  sudo: yes
  notify: reload nginx
  template: dest=/usr/local/etc/nginx/nginx.conf
            src=nginx.conf.j2

- name: sites-available config
  notify: reload nginx
  tags: www
  sudo: yes
  template:
    dest: "/usr/local/etc/nginx/sites-available/{{ item.name }}"
    src:  "www_sites/{{ item.src }}"
  with_items: www_sites

- name: sites-enabled link
  notify: reload nginx
  tags: www
  sudo: yes
  file:
    dest:  "/usr/local/etc/nginx/sites-enabled/{{ item.name }}"
    src:   "/usr/local/etc/nginx/sites-available/{{ item.name }}"
    state: "{{ 'link' if item.enabled | default(true) else 'absent' }}"
  with_items: www_sites

- name: nginx enabled and started
  tags: www
  sudo: yes
  service: name=nginx enabled=yes state=started
