---
- name: enable local_unbound
  tags: unbound
  sudo: yes
  copy:
    dest:    /etc/rc.conf.d/local_unbound
    content: 'local_unbound_enable="YES"'

- name: start local_unbound
  tags: unbound
  sudo: yes
  service:
    name: local_unbound
    state: started

- name: set access control
  tags: unbound
  sudo: yes
  template:
    dest:  /var/unbound/conf.d/access-control.conf
    src:   access-control.conf.j2
    owner: root
    group: unbound
    mode:  0644
  when: unbound_access_control|length > 0
