#!/bin/sh

if [ `id -u` != 0 ]; then
	echo Must be root
	exit 1
fi

DOTFILES=$(realpath $(dirname $0)/..)

install-dir() {
	cp -PRvp $DOTFILES/$1 $PREFIX/
	chown -vv -R 0:0 $PREFIX/$1
} 

install-link() {
	local dest=$PREFIX/$2
	if [ -d $(dirname $dest) ]; then
		ln -fsv $(realpath $DOTFILES/$1) $dest
	else
		echo Directory $(dirname $dest) does not exist.
		echo Skipped linking $DOTFILES/$1
	fi
}

install-dir etc
install-dir root

install-link root/DAEMONIK usr/src/sys/amd64/conf/DAEMONIK
