#!/bin/sh
SRC=/usr/src
LOG=/var/log/buildkernel.log

if [ -e $LOG ]; then
    rm $LOG
fi

if [ -n "${1}" ]; then
    KERNCONF="KERNCONF=${1}"
fi

make -C ${SRC} ${KERNCONF} buildkernel 2>&1 | tee $LOG
