#!/bin/sh

SRC=/usr/src
LOG=/var/log/buildworld.log
CPUS=$(sysctl -n kern.smp.cpus)

if [ -e $LOG ]; then
    rm $LOG
fi

make -C ${SRC} -j $((CPUS*2)) buildworld 2>&1 | tee $LOG
sendmail root << EOF
Subject: Build Completed

Your build of FreeBSD world is done.
EOF
