#!/bin/sh

SRC=/usr/src
CONF=/etc/src.conf.installworld
LOG=/var/log/installworld.log

if [ -e ${CONF} ]; then
    SRCCONF="SRCCONF=${CONF}"
fi

if [ -e $LOG ]; then
    rm $LOG
fi

make -C ${SRC} ${SRCCONF} installworld 2>&1 | tee $LOG &&
make -C ${SRC} ${SRCCONF} delete-old   2>&1 | tee $LOG

