---
- name: backup group
  group: name={{ backup_group | mandatory }} state=present

- name: backup group members
  user: name={{ item }} groups={{ backup_group }} append=yes
  with_items: backup_users

- name: backup dir permissions
  file: name={{ backup_root }}
        state=directory
        mode=770
        group={{ backup_group }}
