---
- hosts: FreeBSD
  roles:
  - freebsd/etc/make.conf
  - freebsd/etc/mergemaster.rc
  - freebsd/etc/motd
  - freebsd/etc/rc.conf.d/hostname
  - freebsd/etc/rc.conf.d/network
  - freebsd/etc/rc.conf.d/routing
  - freebsd/etc/rc.conf.d/sshd
  - freebsd/etc/rc.conf.d/syslogd
  - freebsd/etc/rc.conf.d/zfs
  - freebsd/etc/src.conf
  - freebsd/etc/src.conf/without_tcsh
  - freebsd/etc/src.conf/without_sendmail
  - freebsd/etc/sshd_config
  - freebsd/etc/sysctl.conf/hw.syscons.bell

  - freebsd/svn-usr.src
  - freebsd/svn-usr.src-periodic
  - freebsd/portsnap-periodic

  - freebsd/port/ansible
  - freebsd/port/beadm
  - freebsd/port/portmaster
  - freebsd/port/rsync
  - freebsd/port/sudo

  - freebsd/kernconf
  - freebsd/portmaster
  - freebsd/pf
  - freebsd/sudoers-wheel
  - freebsd/zfs

  - julie/freebsd-software
  - julie/common
  - freebsd/login-shell

- hosts: bydlenka
  roles:
  - crashplan
  - file-server-home
  - file-server-backup
  - file-server-downloads
  - download-server
  - www-server
  - easyrsa-client
  - openvpn/client

- hosts: Darwin
  roles:
  - julie/darwin-software
  - julie/common
  - julie/torrent-uploader
  - darwin/login-shell
  - easyrsa-client
