#!/usr/bin/env ansible-playbook
---
- hosts: FreeBSD
  roles:
  - freebsd/etc/make.conf
  - freebsd/etc/mergemaster.rc
  - freebsd/etc/motd
  - freebsd/etc/rc.conf.d/hostname
  - freebsd/etc/rc.conf.d/network
  - freebsd/etc/rc.conf.d/routing
  - freebsd/etc/rc.conf.d/sshd
  - freebsd/etc/rc.conf.d/syslogd
  - freebsd/etc/rc.conf.d/zfs
  - freebsd/etc/src.conf
  - freebsd/etc/sshd_config
  - freebsd/etc/sysctl.conf/hw.syscons.bell

  - freebsd/svn-usr.src
  - freebsd/svn-usr.src-periodic
  - freebsd/portsnap-periodic

  - freebsd/port/ansible
  - freebsd/port/beadm
  - freebsd/port/portmaster
  - freebsd/port/rsync
  - freebsd/port/sudo

  - freebsd/kernconf
  - freebsd/portmaster
  - freebsd/pf
  - freebsd/sudoers-wheel
  - freebsd/zfs

  - julie/freebsd-software
  - julie/common
  - freebsd/login-shell

- hosts: bydlenka
  roles:
  - crashplan
  - cyrus-sasl
  - file-server-home
  - file-server-backup
  - file-server-downloads
  - download-server
  - www-server

- hosts: demonka
  roles:
  - unbound
  - znc

  - role:    openvpn/server
    openvpn: "{{ openvpn_tcp }}"

  - role:    openvpn/server
    openvpn: "{{ openvpn_udp }}"

  - role:    openvpn/provision-client-viscosity
    user:    julie
    client:  julie-mba
    servers: "{{ demonka_openvpn_servers }}"

  - role:    openvpn/provision-client-viscosity
    user:    julie
    client:  julie-mbpr
    servers: "{{ demonka_openvpn_servers }}"

  - role:    openvpn/provision-client-freebsd
    user:    julie
    client:  bydlenka
    servers:
    - remote:   "{{ demonka_openvpn_remote }}"
      instance: "{{ openvpn_udp }}"

- hosts: bydlenka
  roles:
  - easyrsa-client
  - openvpn/client
