---
- name: config directory
  tags: openvpn
  sudo: yes
  file:
    dest:  "{{ item }}"
    state: directory
  with_items:
  - "{{ openvpn_etc }}"

- include: '../../tasks/chroot-dirs.yml'

- name:   link openvpn service instance
  tags:   openvpn
  sudo:   yes
  notify: openvpn restarted
  file:
    dest:  "/usr/local/etc/rc.d/{{ item }}"
    src:   "/usr/local/etc/rc.d/openvpn"
    state: link
  with_items:
  - "{{ openvpn.name | default(openvpn_name) }}"
  when: item != 'openvpn'

- name:   ensure openvpn.confs
  tags:   openvpn
  sudo:   yes
  notify: openvpn restarted
  template:
    dest: "{{ openvpn_etc }}/{{ item }}.conf"
    src:  ../../templates/openvpn.conf.j2
  with_items:
  - "{{ openvpn.name | default(openvpn_name) }}"

- name: tls-auth key
  tags: openvpn
  sudo: yes
  notify: openvpn restarted
  command: >
    /usr/local/sbin/openvpn
    --genkey
    --secret "/usr/local/etc/openvpn/{{ item }}.ta-key"
  args:
    creates: "/usr/local/etc/openvpn/{{ item }}.ta-key"
  with_items:
  - "{{ openvpn.name | default(openvpn_name) }}"

- name: openvpn services enabled
  tags: openvpn
  sudo: yes
  copy:
    dest: /etc/rc.conf.d/{{ item }}
    content: '{{ item }}_enable="YES"'
  with_items:
  - "{{ openvpn.name | default(openvpn_name) }}"
