#!/bin/sh

    TMUX_DIR="${HOME}/.jachymko/tmux"
DEFAULT_CONF="${TMUX_DIR}/tmux.conf"
 MASTER_CONF="${TMUX_DIR}/tmux.conf.master"

session='default'
 config="${DEFAULT_CONF}"
   tmux=`which tmux`
   cmds=''

if [ ! -x "${tmux}" ]; then
    exit 0
fi

if [ -n "${PARENT_TMUX}" ]; then
    exit 0
fi

if [ -n "${SSH_CONNECTION}" -a -n "${TMUX}" ]; then
    exit 0
fi

if [ -z "${TMUX}" -a -z "${SSH_CONNECTION}" ]; then
    # use tmux.conf.master
    config="${MASTER_CONF}"
    session='master'

    # use independent server
    tmux="${tmux} -L master"
fi

if [ -n "${TMUX}" ]; then
    PARENT_TMUX=${TMUX}
    unset TMUX
    export PARENT_TMUX
fi

if ${tmux} has-session -t ${session} 2> /dev/null; then
    cmds="attach-session -t ${session}; "
else
    if [ -n "${PARENT_TMUX}" ]; then
        cmds="set-environment -g PARENT_TMUX '${PARENT_TMUX}'; "
    fi

    if [ -n "${PARENT_TMUX}" -o -n "${SSH_CONNECTION}" ]; then
        cmds="${cmds} new-session -s ${session}; "
        cmds="${cmds} split-window -h; "
    else
        cmds="new-session -s ${session} -n $(hostname -s); "
    fi
fi

exec ${tmux} -f ${config} ${cmds}
