#!/bin/sh

reattach="$(which reattach-to-user-namespace)"
shell="${SHELL}"

if [ ! -x "${shell}" ]; then
    shell='/bin/sh'
fi

if [ -x "${reattach}" ]; then
    exec ${reattach} -l ${shell}
else
    exec ${shell} -l
fi
