#!/usr/bin/env zsh

if [[ ! -x `which osascript` ]] then
    echo osascript not available
    return 1
fi

itunes_pid=`killall -s iTunes 2>/dev/null | awk '{print $3}'`

current-player-state() {
    [[ -z "$itunes_pid" ]] && return 1
    [[ `osascript -e 'tell application "iTunes" to player state as string'` == 'playing' ]] || return 1
}

current-artist() {
    osascript -e 'tell application "iTunes" to artist of current track as string'
}

current-track() {
    osascript -e 'tell application "iTunes" to name of current track as string'
}

play() {
    local playlist='Terminal playlist'
    osascript - <<EOS
        tell application "iTunes"
            if (exists playlist "$playlist") then
                delete playlist "$playlist"
            end if
            set name of (make new playlist) to "$playlist"

            set theseTracks to every track of playlist "Library" whose artist contains "$1"
            repeat with thisTrack in theseTracks
                duplicate thisTrack to playlist "$playlist"
            end repeat

            set theseTracks to every track of playlist "Library" whose album contains "$1"
            repeat with thisTrack in theseTracks
                duplicate thisTrack to playlist "$playlist"
            end repeat

            set theseTracks to every track of playlist "Library" whose name contains "$1"
            repeat with thisTrack in theseTracks
                duplicate thisTrack to playlist "$playlist"
            end repeat

            play playlist "$playlist"
        end tell
EOS
}

if [[ -z "$1" ]] then
    current-player-state && (current-artist; current-track)
else
    play $1 && print "Playing `current-artist` - `current-track`."
fi
