#!/bin/sh

# show what we are running
uname -v && echo

# and who's been here lately
[ -x "`which lastlogin`" ] && lastlogin && echo

# say somenthing nice. or offensive.
[ -x "`which fortune`" ] && fortune -a && echo
