#!/bin/sh

##
## Find a tmux session without an attached client
## Output: the session name
## Exit code: 0 if found, 1 otherwise
##

result=$(tmux ls -F '#{session_attached} #{session_name}' 2>/dev/null |
         grep ^0 |
         awk '{ print $2 }' |
         head -n 1
)

[[ -n "$result" ]] && echo $result || return 1
