#!/usr/bin/env zsh

if [[ ! -x `which tmux` ]] then
    return 1
fi

if [[ -n "$TMUX" ]] then
    # already inside tmux
    return 1
fi

# use alternate tmux config, if available
if [[ -r "$1" ]] then
    tmuxargs="-f $1"
fi

# attach to the first available abandoned session
# or create a new one
if tmuxsession=`tmux-unattached-session-name` then
    tmux ${=tmuxargs} attach-session -t $tmuxsession
else
    tmux ${=tmuxargs} new-session
fi

return 0
