[[ -z "$TMUX" ]]      &&
[[ -z "$SSH_TTY" ]]   &&
[[ -x `which tmux` ]] &&
tmux-attach-or-new    &&
exit

uname -a

[ -x `which lastlogin` ] &&
lastlogin                &&
echo

[[ -x `which fortune` ]] &&
fortune -a               &&
echo
