alias ll='ls -aFl'

ZSH=$JACHYMKO/zsh/oh-my-zsh
ZSH_THEME="jreese"

COMPLETION_WAITING_DOTS="true"
DISABLE_AUTO_UPDATE="true"
DISABLE_LS_COLORS="true"
# DISABLE_AUTO_TITLE="true"

plugins=(git osx vi-mode)
source $ZSH/oh-my-zsh.sh
