---
- name: enabled
  tags: pf
  become: yes
  copy:
    dest: /etc/rc.conf.d/pf
    content: "pf_enable=\"YES\""

- name: started
  tags: pf
  become: yes
  service:
    name: pf
    state: started

- name: pf.conf
  tags: pf
  become: yes
  notify: reload pf.conf
  template:
    dest: /etc/pf.conf
    src: pfconfs/{{ pfconf }}
    validate: /sbin/pfctl -nf %s

