---
- name: directories
  tags: easyrsa
  become: yes
  file: dest={{ item }}
        state=directory
  with_items:
  - "{{ easyrsa_cadir }}"
  - "{{ easyrsa_keydir }}"

- name: vars
  tags: easyrsa
  become: yes
  template:
    dest={{ easyrsa_cadir | mandatory  }}/vars
    src=vars.j2

- name: index files
  tags: easyrsa
  become: yes
  copy:
    dest: "{{ easyrsa_keydir }}/{{ item.name }}"
    content: "{{ item.content|default('') }}"
    force: no
  with_items:
  - name: 'index.txt'
  - name: 'serial'
    content: '01'


- name: dh
  tags: easyrsa
  become: yes
  shell: >
    . {{ easyrsa_cadir  }}/vars &&
    {{ easyrsa_root }}/build-dh
  args:
    creates: "{{ easyrsa_keydir }}/dh1024.pem"

- name: ca cert
  tags: easyrsa
  become: yes
  shell: >
    . {{ easyrsa_cadir  }}/vars &&
    {{ easyrsa_root }}/pkitool --initca "{{ easyrsa_cacn }}"
  args:
    creates: "{{ easyrsa_keydir }}/ca.key"

- name: pkcs12 passphrase file
  tags: easyrsa
  become: yes
  copy:
    dest:    "{{ easyrsa_keydir }}/pkcs12.passphrase"
    content: "{{ easyrsa_pfx_pass }}"
    owner: root
    group: wheel
    mode: 0600

