---
- include: ca.yml

- include:    certs.yml
  certs:      "{{ easyrsa_server_certs }}"
  cert_files: [ crt, key, pem ]
  cert_kind:  '--server'

- include:    certs.yml
  certs:      "{{ easyrsa_certs }}"
  cert_files: [ crt, key, pem, pfx ]
