---
- name: ensure sudoers.d included
  sudo: yes
  lineinfile:
    dest: /usr/local/etc/sudoers
    line: '#includedir /usr/local/etc/sudoers.d'

- name: allow wheel
  sudo: yes
  copy:
    dest: /usr/local/etc/sudoers.d/wheel
    content: "%wheel ALL=(ALL) ALL"
    create: yes
